version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: smolgrrr-wired_web_1
      APP_PORT: 42069
      PROXY_AUTH_ADD: "false"

  web:
    image: smolgrrr/tao:v0.1.2@sha256:3de27e272fb8105ad5de2932222c7c87d34b28746b34e6a939271ad66622d9b2
    restart: on-failure
    stop_grace_period: 1m
  
  server:
    image: smolgrrr/tao-pow-server:v0.1.1@sha256:203b079c01714168f458e66d543e2a4984be5a1860082d0bf0d69881010775a6
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 42068:42068