version: "3.7"

services:
    bitcoin:
    container_name: bitcoin
    image: nolim1t/bitcoinknots
    depends_on:
    - tor
    volumes:
    - ${PWD}/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - 8332:8332
    networks:
        default:
        ipv4_address: "10.21.0.4"
