version: "3"

services:
  bitcoin:
    container_name: bitcoin
    image: nolim1t/bitcoinknots:v0.21.1.knots20210629
    volumes:
      - ${PWD}/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8332:8332"
      - "8333:8333"
    networks:
      default:
        ipv4_address: "10.21.0.4"
